# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kakao-Clone-New' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kakao-Clone-New
  pod 'SnapKit', '~> 4.0'
  pod 'Then'
  pod 'Alamofire', '~> 5.2'

end
